### ISSUE TITLE
[[css问题]]：请问立青这个图片里的红色目录标识是怎么做出来的？求分享!

### ISSUE THREAD

**Issue by aka-phrankie** [JimmyLv/roam-productivity#15]
颜值比手动Emoji标识简洁多了。

![目录红小圆点](https://i0.hdslb.com/bfs/article/2ad2d6c9061e799d7abc12c4b19c6ec0c46fa7de.png)

**Comment by JimmyLv** [comment]
哈哈哈 这是我截图之后，手动标注的！！ CleanShot X
